### ISSUE TITLE
Plugin MediaDownloader crash

### ISSUE THREAD

**Issue by Dima73** [oe-alliance/enigma2-plugins#688]
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/StartEnigma.py", line 217, in processDelay
    callback(*retval)
  File "/usr/lib/enigma2/python/Plugins/Extensions/MediaDownloader/MediaDownloader.py", line 191, in gotFilename
    self.fetchFile()
  File "/usr/lib/enigma2/python/Plugins/Extensions/MediaDownloader/MediaDownloader.py", line 198, in fetchFile
    d = download(
  File "/usr/lib/enigma2/python/Plugins/Extensions/MediaDownloader/MediaDownloader.py", line 116, in download
    factory = HTTPProgressDownloader(url, file, writeProgress, *args, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/MediaDownloader/HTTPProgressDownloader.py", line 8, in __init__
    HTTPDownloader.__init__(self, url, fileOrName, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/twisted/web/client.py", line 515, in __init__
  File "/usr/lib/python3.9/site-packages/twisted/web/client.py", line 375, in __init__
  File "/usr/lib/python3.9/site-packages/twisted/web/client.py", line 398, in setURL
  File "/usr/lib/python3.9/site-packages/twisted/web/_newclient.py", line 634, in _ensureValidURI
TypeError: cannot use a bytes pattern on a string-like object

**Comment by Dima73** [comment]
https://github.com/OpenPLi/enigma2-plugins/pull/1005
